stages:
 - build
 - javadoc
 - sonar
 
build:
 stage: build
 script: "mvn clean package -B"
 tags:
  - java
  
javadoc:
  stage: javadoc
  script:
   - "mvn javadoc:aggregate --fail-never"
   - "sh -c \"scp -rC ./target/site/apidocs root@doc.2dfire-daily.com:/usr/share/nginx/javadoc/${PWD##*/}\""
 tags:
  - java
 only:
  - master
 
sonar:
 stage: sonar
 script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent test checkstyle:checkstyle sonar:sonar
 tags:
  - java
 only:
  - master